server:
  port: 8190
  servlet:
    context-path: /market-cart
integrations:
  product-service:
    url: http://localhost:8189/market-core/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
cart-service:
  cart-prefix: march_cart_

